name: korey.larkin
description: 5th generation
version: 0.0.1
author: 6pbkyiw0.8ulbwghg@58ppvqu6.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: koreylarkin
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2024-11-22 20:14:33'
pipelines:
  pipelines/Breana_TurnerJack_HammerKing_Medhurst:
    name: Breana_TurnerJack_HammerKing_Medhurst
    description: null
    author: 6pbkyiw0.8ulbwghg@58ppvqu6.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-11-22 20:14:33'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-11-22 20:14:33'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-11-22T20:14:33.317148Z'
  name: plibMaven
  version: 8.6.0-SNAPSHOT
  id: '1067916846'
  createdAt: '2024-11-22T20:14:33.317148Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
